// hoox/src/index.ts - Public-facing gateway for TradingView

import { IdempotencyStore } from "./idempotencyStore";
import { createRateLimiter } from "@jango-blockchained/hoox-shared/middleware";
import {
  Errors,
  toError,
  createJsonResponse,
} from "@jango-blockchained/hoox-shared/errors";
import {
  createLogger,
  withRequestLog,
  validateJson,
  secureHeaders,
} from "@jango-blockchained/hoox-shared/middleware";
import { createRouter } from "@jango-blockchained/hoox-shared/router";
import {
  WebhookPayloadSchema,
  type WebhookPayload,
  type StandardResponse,
} from "@jango-blockchained/hoox-shared/types";
import { trackAnalytics } from "@jango-blockchained/hoox-shared/analytics";
import { healthCheck } from "@jango-blockchained/hoox-shared/health";
import { KVKeys } from "@jango-blockchained/hoox-shared/kvKeys";
import { serviceFetch } from "@jango-blockchained/hoox-shared/service-bindings";
import {
  DISCLAIMER,
  DISCLAIMER_HEADER,
} from "@jango-blockchained/hoox-shared/legal";

import {
  TradeData,
  NotificationData,
  ServiceResponse,
  QueueMode,
} from "./types";
import { validateApiKeyBinding } from "./utils/security";
import { handleRequest } from "./handlers/webhook";
import {
  getQueueMode,
  checkIdempotency,
  sendTradeToQueue,
  processTrade,
  processNotification,
  createDefaultMessage,
} from "./logic";

// --- Rate limiting limits (passed to KV-backed rate limiter) ---
const MAX_TRADES_PER_MINUTE = 10;
const RATE_LIMIT_WINDOW = 60; // 60 seconds

async function checkRateLimit(sessionId: string, env: any): Promise<boolean> {
  const kv = env.CONFIG_KV;
  const rateLimiter = createRateLimiter(kv, {
    maxRequests: MAX_TRADES_PER_MINUTE,
    windowSeconds: RATE_LIMIT_WINDOW,
    keyPrefix: "hoox-webhook",
  });
  const result = await rateLimiter.checkKey(sessionId);
  return result.allowed;
}

// --- Default Export (Worker Entry Point) ---
// Env type is fully generated by wrangler types (worker-configuration.d.ts)
// No manual Env interface needed — bindings are inherited from Cloudflare.Env

const logger = createLogger({ service: "hoox-gateway", module: "router" });

const router = createRouter<Env>();

// Define routes
router.post(
  "/webhook",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    return await handleRequest(request, env, ctx, logger, {
      wrapResponse,
      checkRateLimit,
      processTrade: (data: TradeData, env: Env, mode: QueueMode) =>
        processTrade(
          data,
          env,
          logger,
          {
            checkIdempotency: (env, key, logger) =>
              checkIdempotency(env, key, logger),
            sendTradeToQueue: (queue, data, logger) =>
              sendTradeToQueue(queue, data, logger),
            MAX_TRADES_PER_MINUTE,
          },
          mode
        ),
      processNotification: (data, env) =>
        processNotification(data, env, logger),
      getQueueMode,
      createDefaultMessage,
    });
  }
);

router.get(
  "/health",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    const response = healthCheck({ worker: "hoox" });
    return wrapResponse(response);
  }
);

export default {
  fetch: withRequestLog<Env>(
    async (request: Request, env: Env, ctx: ExecutionContext) => {
      // Proxy /wallet/* paths to web3-wallet-worker via service binding
      const url = new URL(request.url);
      if (url.pathname.startsWith("/wallet")) {
        const internalPath = url.pathname.replace(/^\/wallet/, "") || "/";
        const response = await env.WEB3_WALLET_SERVICE.fetch(
          new Request(`http://internal${internalPath}`, {
            method: request.method,
            headers: request.headers,
            body: request.body,
            signal: AbortSignal.timeout(10_000),
          })
        );
        return wrapResponse(response);
      }
      return router.handle(request, env, ctx);
    },
    { service: "hoox-gateway", module: "router" }
  ),
};

/**
 * Wraps a response with security headers and legal disclaimer.
 * Uses shared middleware for standardized security headers.
 */
function wrapResponse(response: Response): Response {
  // Apply security headers from shared middleware with extended CSP
  const headers = new Headers(response.headers);
  const securityHeaders = secureHeaders({
    contentSecurityPolicy: `default-src 'self'; script-src 'self'`,
  });
  for (const [key, value] of Object.entries(securityHeaders)) {
    headers.set(key, value);
  }
  // Add legal disclaimer header
  headers.set(DISCLAIMER_HEADER, DISCLAIMER);
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

export { IdempotencyStore };
