/**
 * Copyright (c) 2026 HOOX · HOOX · jango-blockchained (hoox-sh)
 * SPDX-License-Identifier: Apache-2.0
 */

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Reports | Hoox Dashboard",
  description:
    "PDF and CSV reports generated by the report-worker (cron: 06:00 and 18:00 UTC). Filter, download, and regenerate on demand.",
};
